import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/lib/contexts/AuthContext";
import CustomNavbar from "@/components/CustomNavbar";
import { CartProvider } from "@/lib/contexts/CartContext";
import CartSidebar from "@/components/cart/CartSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <AuthProvider>
          <CustomNavbar/>
          <CartSidebar/>
          {children}
        </AuthProvider>
        </CartProvider>
        
      </body>
    </html>
  );
}
